# Generated by Django 4.2.7 on 2023-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
            ],
        ),
    ]
